# Generated by Django 3.1 on 2020-08-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Título')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Estatura')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': '',
            },
        ),
    ]
