# Generated by Django 3.1 on 2020-08-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre enfermedad')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('tratamietno', models.TextField(verbose_name='tratamiento')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'enfermedad',
                'verbose_name_plural': 'enfermedades',
                'ordering': '',
            },
        ),
    ]
