# Generated by Django 3.1 on 2020-08-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_auto_20200827_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='section',
            field=models.CharField(default='cabeza', max_length=200, verbose_name='sección del cuerpo'),
            preserve_default=False,
        ),
    ]
