# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - apt-get update
            - apt-get -qq install ncftp
            - npm install
            - npm run build
            - ncftpput -R -v -u $FTP_USERNAME -p $FTP_PASSWORD -P 21 ftp.dominioestudio.info cursos-ecopetrol/gestion-basica-hse dist/*